#! /usr/bin/env bash

# get wireless private IP
private_w_IP(){
    hostname -I | cut -d ' ' -f1
}

# Multipoupuse compress files extractor
ex(){
    local filepath="${1%/*}"
    if [ -f "$1" ]; then
        case "$1" in
            *.zip)  unzip   "$1"  ;;        
            *.7z)   7z e    "$1"  ;;        
            *.tar.gz)  tar -xvf   "$1"
        esac
    else
        printf %s\\n "$1 no es un directorio"
    fi
}

# Multipourpuse file opener
open(){
    if [ -f "$1" ] ; then
        case "$1" in
            *.7z)   7z l "$1" ;;
            *.zip)  zip l "$1" ;;
            *.png)  sxiv "$1" ;; 
            *.jpg)  sxiv "$1" ;; 
            *.JPG)  sxiv "$1" ;; 
            *.PNG)  sxiv "$1" ;; 
            *.pdf)  xdg-open "$1" 2>/dev/null;; 
            *.html) xdg-open "$1" 2>/dev/null;; 
            *.sh) xdg-open "$1" 2>/dev/null;; 
            *.py) xdg-open "$1" 2>/dev/null;;
        esac
   else
        printf %s\\n "$1 no es un directorio"
   fi
}

# Convert dir to zip file
dir2zip(){
    if [ -d "$1" ]; then
       echo "$1" 
    else
        printf %s\\n "No es un directorio"
    fi
}

# File system check for drives
check_drive(){
    local drive
    if [ -z "$1" ]; then
        drive="/dev/sda"
    else
        drive="$1"
    fi
    sudo fsck "$drive"
}

# get git branch
git_branch(){
    git branch --show-current 2>/dev/null 
}

# get dir size. It does not return dir's files size
dir_size(){
    echo "$(ls -hal | head -n 1 | cut -d ' ' -f 2)b" 
}

# find file in dirs
files_in_dir(){
    echo "$(find . -maxdepth 1 -type f| wc -l) files"
}
# Get yout public IP
public_IP(){
    timeout 1 curl ipinfo.io/ip || echo "no-ip"
}

# get user name. Root user is printed in red
get_user(){
    if [ "$USER" == "root" ]; then
        echo -e "\e[0;1;38;5;160mroot\e[0m"
    else
        echo -e "\e[0;1;38;5;153m$USER\e[0m"
    fi
}

# Set pretty colors in less
man() {
    # Based in: https://felipec.wordpress.com/2021/06/05/adventures-with-man-color/
    #LESS_TERMCAP_md=$'\e[01;31m' \
    LESS_TERMCAP_md=$'\e[0;1;38;5;196m' \
    LESS_TERMCAP_me=$'\e[0m' \
    LESS_TERMCAP_so=$'\e[0;38;5;232;48;5;226m' \
    LESS_TERMCAP_se=$'\e[0m' \
    LESS_TERMCAP_us=$'\e[0;38;5;117m' \
    LESS_TERMCAP_ue=$'\e[0m' \
    command man "$@"
}

# HTML to Markdown converter
html2md(){
    local file="$1"
    local encoding='utf8'
    local width= 
        case "$1" in
        esac
    html2text --pretty "$encoding"
}

# Enable pyrhont enviroment
set_pyenviroment(){
    local dir_name="$(ls -al | grep -i "env" | rev | cut -d' ' -f1 | rev)" # Recoge el nombre final del archivo
    printf %s\\n "Enviroment dir: $dir_name"

    source "$dir_name/bin/activate"
}


writecmd (){ perl -e 'ioctl STDOUT, 0x5412, $_ for split //, do{ chomp($_ = <>); $_ }' ; }

# forward history
fh() {
    # https://github.com/junegunn/fzf/wiki/examples
  ([ -n "$ZSH_NAME" ] && fc -l 1 || history) | cut -d' ' -f4- | uniq | fzf +s --tac -i | sed -re 's/^\s*[0-9]+\s*//' |  writecmd
}

# cd + ls
ch(){
    if [ "$#" -ne 0 ]; then
        builtin cd "$*" && ls
    else
        builtin cd && ls
    fi
}

# check tor enviroment
check_tor(){
    [ -n "$LD_PRELOAD" ] && echo "Tor"
}

# Enable tor enviroment
set_torenviroment(){
    torsocks --shell
}
